-- Doorway readings are generated by the webhook for buyers who have no auth
-- session yet: user_id becomes nullable. Email is their claim key (/api/read/mine).
-- RLS unchanged: auth.uid() = user_id never matches null → null rows are
-- invisible to clients, service-role only, until claimed.
-- APPLIED to cityflow (uwwquvnvxcmahsweuywl) 2026-06-12 via MCP.
alter table public.astrolabe_readings alter column user_id drop not null;
